-- StockLume PostgreSQL schema for a fresh Supabase database.
-- Apply this file once with the Supabase SQL editor or a PostgreSQL client.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_symbol UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS simulation_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    starting_balance NUMERIC(18, 2) NOT NULL DEFAULT 100000.00,
    cash_balance NUMERIC(18, 2) NOT NULL DEFAULT 100000.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_simulation_account_user UNIQUE (user_id),
    CONSTRAINT chk_simulation_starting_balance CHECK (starting_balance >= 0),
    CONSTRAINT chk_simulation_cash_balance CHECK (cash_balance >= 0)
);

CREATE TABLE IF NOT EXISTS simulation_holdings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    quantity NUMERIC(18, 6) NOT NULL,
    average_price NUMERIC(18, 4) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_simulation_holding_user_symbol UNIQUE (user_id, symbol),
    CONSTRAINT chk_simulation_holding_quantity CHECK (quantity > 0),
    CONSTRAINT chk_simulation_holding_average_price CHECK (average_price > 0)
);

CREATE TABLE IF NOT EXISTS simulation_trades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    trade_type VARCHAR(8) NOT NULL,
    quantity NUMERIC(18, 6) NOT NULL,
    price NUMERIC(18, 4) NOT NULL,
    total_value NUMERIC(18, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_simulation_trade_type CHECK (trade_type IN ('BUY', 'SELL')),
    CONSTRAINT chk_simulation_trade_quantity CHECK (quantity > 0),
    CONSTRAINT chk_simulation_trade_price CHECK (price > 0),
    CONSTRAINT chk_simulation_trade_total CHECK (total_value > 0)
);

CREATE INDEX IF NOT EXISTS idx_simulation_trades_user_created_at
    ON simulation_trades (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS api_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(255) NOT NULL UNIQUE,
    data_type VARCHAR(50) NOT NULL,
    symbol VARCHAR(32),
    response_data JSONB NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_api_cache_expires_at ON api_cache (expires_at);
CREATE INDEX IF NOT EXISTS idx_api_cache_symbol_type ON api_cache (symbol, data_type);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS simulation_accounts_set_updated_at ON simulation_accounts;
CREATE TRIGGER simulation_accounts_set_updated_at
BEFORE UPDATE ON simulation_accounts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS simulation_holdings_set_updated_at ON simulation_holdings;
CREATE TRIGGER simulation_holdings_set_updated_at
BEFORE UPDATE ON simulation_holdings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
