import sys
import unittest
from pathlib import Path
from unittest.mock import patch

from fastapi import HTTPException
from psycopg.errors import UniqueViolation


BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

from routes import auth_routes
from schemas.auth import RegistrationData
from services.watchlist_service import add_watchlist_item, delete_watchlist_item


class FakeConnection:
    def __init__(self, cursor):
        self.cursor_value = cursor
        self.committed = False
        self.rolled_back = False

    def cursor(self):
        return self.cursor_value

    def commit(self):
        self.committed = True

    def rollback(self):
        self.rolled_back = True

    def close(self):
        pass


class FakeCursor:
    def __init__(self, results=(), insert_error=None):
        self.results = list(results)
        self.insert_error = insert_error
        self.rowcount = 1
        self.queries = []

    def execute(self, query, params):
        self.queries.append((" ".join(query.split()), params))
        if self.insert_error and "INSERT INTO users" in query:
            raise self.insert_error

    def fetchone(self):
        return self.results.pop(0) if self.results else None

    def close(self):
        pass


class PostgreSQLMigrationTests(unittest.TestCase):
    def test_registration_success_uses_existing_response(self):
        cursor = FakeCursor(results=[None])
        connection = FakeConnection(cursor)

        with patch.object(auth_routes, "get_db_connection", return_value=connection), \
             patch.object(auth_routes, "enforce_client_rate_limit"), \
             patch.object(auth_routes, "hash_password", return_value="hash"):
            response = auth_routes.register(
                RegistrationData(name="Ada", email="ada@example.com", password="password1"),
                request=object()
            )

        self.assertEqual(response, {"message": "User added successfully"})
        self.assertTrue(connection.committed)

    def test_unique_violation_returns_duplicate_email_conflict(self):
        cursor = FakeCursor(results=[None], insert_error=UniqueViolation("duplicate"))
        connection = FakeConnection(cursor)

        with patch.object(auth_routes, "get_db_connection", return_value=connection), \
             patch.object(auth_routes, "enforce_client_rate_limit"), \
             patch.object(auth_routes, "hash_password", return_value="hash"):
            with self.assertRaises(HTTPException) as error:
                auth_routes.register(
                    RegistrationData(name="Ada", email="ada@example.com", password="password1"),
                    request=object()
                )

        self.assertEqual(error.exception.status_code, 409)
        self.assertTrue(connection.rolled_back)

    def test_watchlist_insert_uses_conflict_handling_and_returning_id(self):
        cursor = FakeCursor(results=[{"id": 42}])

        self.assertEqual(add_watchlist_item(cursor, 7, "AAPL"), 42)
        query = cursor.queries[0][0]
        self.assertIn("ON CONFLICT (user_id, symbol) DO NOTHING", query)
        self.assertIn("RETURNING id", query)

    def test_watchlist_duplicate_and_missing_delete_keep_existing_statuses(self):
        with self.assertRaises(HTTPException) as duplicate_error:
            add_watchlist_item(FakeCursor(results=[None]), 7, "AAPL")
        self.assertEqual(duplicate_error.exception.status_code, 409)

        cursor = FakeCursor()
        cursor.rowcount = 0
        with self.assertRaises(HTTPException) as delete_error:
            delete_watchlist_item(cursor, 7, "AAPL")
        self.assertEqual(delete_error.exception.status_code, 404)

    def test_schema_uses_postgresql_identities_jsonb_and_timestamp_triggers(self):
        schema = (BACKEND_DIR / "schema.sql").read_text()

        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)
        self.assertIn("JSONB NOT NULL", schema)
        self.assertIn("TIMESTAMPTZ", schema)
        self.assertIn("CREATE TRIGGER simulation_accounts_set_updated_at", schema)
        self.assertIn("CREATE TRIGGER simulation_holdings_set_updated_at", schema)
        self.assertNotIn("AUTO_INCREMENT", schema)
        self.assertNotIn("ON UPDATE CURRENT_TIMESTAMP", schema)


if __name__ == "__main__":
    unittest.main()
