-- PostgreSQL/Supabase migration note.
--
-- StockLume now targets a fresh Supabase PostgreSQL database. Apply
-- ../schema.sql as the single canonical initial schema; it is idempotent and
-- includes the tables, indexes, constraints, and updated_at triggers.
--
-- This file intentionally contains no incremental SQL: the previous version
-- altered an existing MySQL database, and must not be run against Supabase.
